//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace InvoiCyNfeClient.InvoiCyRecepcao {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="recepcaoSoapBinding", Namespace="InvoiCy")]
    public partial class recepcao : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public recepcao() {
            this.Url = global::InvoiCyNfeClient.Properties.Settings.Default.InvoiCyNfeClient_br_com_invoicy_homolog_recepcao;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("InvoiCyaction/ARECEPCAO.Execute", RequestElementName="recepcao.Execute", RequestNamespace="InvoiCy", ResponseElementName="recepcao.ExecuteResponse", ResponseNamespace="InvoiCy", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Invoicyretorno")]
        public Invoicyretorno Execute(InvoiCy Invoicyrecepcao) {
            object[] results = this.Invoke("Execute", new object[] {
                        Invoicyrecepcao});
            return ((Invoicyretorno)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(InvoiCy Invoicyrecepcao) {
            this.ExecuteAsync(Invoicyrecepcao, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(InvoiCy Invoicyrecepcao, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Invoicyrecepcao}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="InvoiCy")]
    public partial class InvoiCy {
        
        private InvoiCyRecepcaoCabecalho cabecalhoField;
        
        private InvoiCyRecepcaoInformacoes informacoesField;
        
        private InvoiCyRecepcaoDadosItem[] dadosField;
        
        /// <remarks/>
        public InvoiCyRecepcaoCabecalho Cabecalho {
            get {
                return this.cabecalhoField;
            }
            set {
                this.cabecalhoField = value;
            }
        }
        
        /// <remarks/>
        public InvoiCyRecepcaoInformacoes Informacoes {
            get {
                return this.informacoesField;
            }
            set {
                this.informacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DadosItem", IsNullable=false)]
        public InvoiCyRecepcaoDadosItem[] Dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InvoiCyRecepcao.Cabecalho", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoCabecalho {
        
        private string empPKField;
        
        private string empCKField;
        
        private string empCOField;
        
        /// <remarks/>
        public string EmpPK {
            get {
                return this.empPKField;
            }
            set {
                this.empPKField = value;
            }
        }
        
        /// <remarks/>
        public string EmpCK {
            get {
                return this.empCKField;
            }
            set {
                this.empCKField = value;
            }
        }
        
        /// <remarks/>
        public string EmpCO {
            get {
                return this.empCOField;
            }
            set {
                this.empCOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InvoiCyRetorno.MensagemItem.DocumentosItem", Namespace="InvoiCy")]
    public partial class InvoiCyRetornoMensagemItemDocumentosItem {
        
        private string documentoField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InvoiCyRetorno.MensagemItem", Namespace="InvoiCy")]
    public partial class InvoiCyRetornoMensagemItem {
        
        private int codigoField;
        
        private string descricaoField;
        
        private InvoiCyRetornoMensagemItemDocumentosItem[] documentosField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentosItem", IsNullable=false)]
        public InvoiCyRetornoMensagemItemDocumentosItem[] Documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="InvoiCy")]
    public partial class Invoicyretorno {
        
        private InvoiCyRetornoMensagemItem[] mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemItem", IsNullable=false)]
        public InvoiCyRetornoMensagemItem[] Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InvoiCyRecepcao.DadosItem", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoDadosItem {
        
        private string documentoField;
        
        private string parametrosField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string Parametros {
            get {
                return this.parametrosField;
            }
            set {
                this.parametrosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="InvoiCyRecepcao.Informacoes", Namespace="InvoiCy")]
    public partial class InvoiCyRecepcaoInformacoes {
        
        private string textoField;
        
        /// <remarks/>
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Invoicyretorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Invoicyretorno)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591